"""SBML Level 3 export for HelixLang GEM models.

Pure-Python SBML XML generation -- no libsbml dependency required.

Module structure:
    export_sbml              write SBML XML to file
    model_to_sbml_string     convert MetabolicModel to SBML XML string
"""
from __future__ import annotations

import datetime
import html
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from helixlang.plugins.runtime.metabolism import MetabolicModel, Reaction


# ---------------------------------------------------------------------------
# XML helpers
# ---------------------------------------------------------------------------

def _esc(text: str) -> str:
    """Escape text for XML content."""
    return html.escape(text, quote=True)


def _sbml_header(model_id: str, organism_name: str) -> str:
    """Return the opening <sbml> element with XMLNS and layout namespaces."""
    now = datetime.datetime.now(datetime.UTC).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    org_attr = (
        f" name=\"{_esc(organism_name)}\"" if organism_name else ""
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<sbml xmlns="http://www.sbml.org/sbml/level3/version1/core"'
        ' xmlns:layout="http://www.sbml.org/sbml/level3/version1/layout/version1"'
        ' level="3" version="1">\n'
        f'  <model id="{_esc(model_id)}"{org_attr}>\n'
        f'    <notes>\n'
        f'      <body xmlns="http://www.w3.org/1999/xhtml">\n'
        f'        <p>Generated by HelixLang GEM pipeline</p>\n'
        f'        <p>Date: {now}</p>\n'
        f'      </body>\n'
        f'    </notes>\n'
    )


SBML_FOOTER = (
    "  </model>\n"
    "</sbml>\n"
)


# ---------------------------------------------------------------------------
# Unit definitions
# ---------------------------------------------------------------------------

def _unit_definitions() -> str:
    """Return SBML <listOfUnitDefinitions> for standard HelixLang units."""
    return (
        '    <listOfUnitDefinitions>\n'
        '      <unitDefinition id="mmol_per_gDW_per_h">\n'
        '        <listOfUnits>\n'
        '          <unit kind="millimole" multiplier="1" scale="0" exponent="1"/>\n'
        '          <unit kind="gram" multiplier="1" scale="0" exponent="-1"/>\n'
        '          <unit kind="second" multiplier="3600" scale="0" exponent="-1"/>\n'
        '        </listOfUnits>\n'
        '      </unitDefinition>\n'
        '      <unitDefinition id="flux">\n'
        '        <listOfUnits>\n'
        '          <unit kind="millimole" multiplier="1" scale="0" exponent="1"/>\n'
        '          <unit kind="gram" multiplier="1" scale="0" exponent="-1"/>\n'
        '          <unit kind="second" multiplier="3600" scale="0" exponent="-1"/>\n'
        '        </listOfUnits>\n'
        '      </unitDefinition>\n'
        '    </listOfUnitDefinitions>\n'
    )


# ---------------------------------------------------------------------------
# Compartments
# ---------------------------------------------------------------------------

def _extract_compartments(metabolites: set[str]) -> dict[str, str]:
    """Infer compartments from metabolite suffixes.

    Convention: ``metabolite_suffix``  (e.g. ``_c``, ``_e``, ``_m``).
    Returns dict of compartment_id -> name.
    """
    comps: dict[str, str] = {}
    for met in metabolites:
        parts = met.rsplit("_", 1)
        if len(parts) == 2 and len(parts[1]) <= 3 and parts[1].isalnum():
            cid = parts[1]
            if cid not in comps:
                comps[cid] = f"compartment_{cid}"
    if not comps:
        comps["c"] = "cytosol"
    return comps


def _compartment_list(comps: dict[str, str]) -> str:
    """Return <listOfCompartments> XML."""
    lines = ['    <listOfCompartments>']
    for cid, name in sorted(comps.items()):
        lines.append(
            f'      <compartment id="{_esc(cid)}"'
            f' name="{_esc(name)}" spatialDimensions="3"'
            f' size="1" constant="true"/>'
        )
    lines.append('    </listOfCompartments>')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Species
# ---------------------------------------------------------------------------

def _species_list(metabolites: set[str], comps: dict[str, str]) -> str:
    """Return <listOfSpecies> XML."""
    lines = ['    <listOfSpecies>']
    for met in sorted(metabolites):
        parts = met.rsplit("_", 1)
        if len(parts) == 2 and len(parts[1]) <= 3 and parts[1].isalnum():
            comp = parts[1]
        else:
            comp = next(iter(comps))
        lines.append(
            f'      <species id="{_esc(met)}" name="{_esc(met)}"'
            f' compartment="{_esc(comp)}" initialConcentration="0"'
            f' hasOnlySubstanceUnits="true" boundaryCondition="false"'
            f' constant="false"/>'
        )
    lines.append('    </listOfSpecies>')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------

def _parameter_list(model: MetabolicModel) -> str:
    """Return <listOfParameters> for default flux bounds."""
    lines = ['    <listOfParameters>']
    lines.append(
        '      <parameter id="default_lower_bound"'
        ' name="default_lower_bound" value="-1000"'
        ' constant="true" units="flux"/>'
    )
    lines.append(
        '      <parameter id="default_upper_bound"'
        ' name="default_upper_bound" value="1000"'
        ' constant="true" units="flux"/>'
    )
    lines.append(
        '      <parameter id="default_irreversible_lower"'
        ' name="default_irreversible_lower" value="0"'
        ' constant="true" units="flux"/>'
    )
    lines.append('    </listOfParameters>')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Reactions
# ---------------------------------------------------------------------------

def _reaction_element(model: MetabolicModel, rxn: Reaction) -> str:
    """Return a single <reaction> XML element with stoichiometry."""
    reversible = rxn.lower_bound < 0

    lines = [
        f'      <reaction id="{_esc(rxn.id)}" name="{_esc(rxn.name)}"'
        f' reversible="{str(reversible).lower()}" fast="false">',
        '        <listOfReactants>',
    ]

    for met, coeff in sorted(rxn.stoichiometry.items()):
        if coeff < 0:
            stoich = abs(coeff)
            lines.append(
                f'          <speciesReference species="{_esc(met)}"'
                f' stoichiometry="{stoich}" constant="true"/>'
            )
    lines.append('        </listOfReactants>')
    lines.append('        <listOfProducts>')
    for met, coeff in sorted(rxn.stoichiometry.items()):
        if coeff > 0:
            lines.append(
                f'          <speciesReference species="{_esc(met)}"'
                f' stoichiometry="{coeff}" constant="true"/>'
            )
    lines.append('        </listOfProducts>')

    # Kinetic bounds
    lines.append('        <kineticLaw>')
    lines.append('          <math xmlns="http://www.w3.org/2008/05/mathml">')
    lines.append('            <ci> flux </ci>')
    lines.append('          </math>')
    lines.append('          <listOfLocalParameters>')
    lines.append(
        f'            <localParameter id="lower_bound"'
        f' value="{rxn.lower_bound}" units="flux"/>'
    )
    lines.append(
        f'            <localParameter id="upper_bound"'
        f' value="{rxn.upper_bound}" units="flux"/>'
    )
    lines.append('          </listOfLocalParameters>')
    lines.append('        </kineticLaw>')

    lines.append('      </reaction>')
    return "\n".join(lines)


def _reaction_list(model: MetabolicModel) -> str:
    """Return <listOfReactions> XML."""
    lines = ['    <listOfReactions>']
    for rxn_id in sorted(model.reactions):
        lines.append(_reaction_element(model, model.reactions[rxn_id]))
    lines.append('    </listOfReactions>')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# GPR annotations
# ---------------------------------------------------------------------------

def _gpr_annotations(model: MetabolicModel) -> str:
    """Return GPR (Gene-Protein-Reaction) annotation elements.

    GPR rules are stored as XML annotation elements under each reaction,
    using a simplified format when available on the reaction subsystem.
    This produces SBML-compatible annotation blocks.
    """
    lines = [
        '    <listOfReactions>',
    ]
    for rxn_id in sorted(model.reactions):
        rxn = model.reactions[rxn_id]
        lines.append(
            f'      <reaction id="{_esc(rxn.id)}">'
        )
        lines.append(
            '        <annotation>'
        )
        lines.append(
            '          <rxn:GPR xmlns:rxn="http://helixlang.org/sbml/gpr">'
        )
        lines.append(
            f'            <rxn:subsystem>{_esc(rxn.subsystem)}</rxn:subsystem>'
        )
        lines.append(
            '          </rxn:GPR>'
        )
        lines.append(
            '        </annotation>'
        )
        lines.append(
            '      </reaction>'
        )
    lines.append(
        '    </listOfReactions>',
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Objective
# ---------------------------------------------------------------------------

def _objective_element(model: MetabolicModel) -> str:
    """Return <listOfObjectives> with biomass as the objective."""
    obj_id = model.biomass_reaction or (
        next(iter(model.reactions), "biomass") or "biomass"
    )
    return (
        '    <listOfObjectives>\n'
        '      <objective id="obj_biomass" type="maximize">\n'
        f'        <listOfFluxObjectives>\n'
        f'          <fluxObjective coefficient="1">\n'
        f'            <reaction reference="{_esc(obj_id)}"/>\n'
        f'          </fluxObjective>\n'
        f'        </listOfFluxObjectives>\n'
        '      </objective>\n'
        '    </listOfObjectives>\n'
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def model_to_sbml_string(
    model: MetabolicModel,
    model_id: str = "helixlang_gem",
    organism_name: str = "",
) -> str:
    """Convert a :class:`MetabolicModel` to an SBML Level 3 XML string.

    Parameters
    ----------
    model:
        The metabolic model to export.
    model_id:
        SBML model identifier.
    organism_name:
        Optional human-readable organism name.

    Returns
    -------
    str
        Complete SBML XML document as a string.
    """
    comps = _extract_compartments(model.metabolites)

    parts: list[str] = [
        _sbml_header(model_id, organism_name),
        _unit_definitions(),
        _compartment_list(comps),
        _species_list(model.metabolites, comps),
        _parameter_list(model),
        _reaction_list(model),
        _objective_element(model),
        _gpr_annotations(model),
        SBML_FOOTER,
    ]
    return "".join(parts)


def export_sbml(
    model: MetabolicModel,
    filepath: str,
    model_id: str = "helixlang_gem",
    organism_name: str = "",
) -> None:
    """Export a :class:`MetabolicModel` to an SBML Level 3 XML file.

    Parameters
    ----------
    model:
        The metabolic model to export.
    filepath:
        Destination path for the ``.xml`` / ``.sbml`` file.
    model_id:
        SBML model identifier.
    organism_name:
        Optional human-readable organism name.

    Returns
    -------
    None

    Raises
    ------
    OSError
        If the file cannot be written.
    """
    xml_string = model_to_sbml_string(model, model_id, organism_name)
    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(xml_string)
